language: node_js
node_js:
- '16.18.1'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=splitwise)
  - secure: pYrQXMG+FoVCGMuawHhkTKlXjgGDBM5KMYCO1U6yeN51k34srY+Q0p9FvMIWoEoZNWBppu1YBYjzM/zUg++d9S12XnabKo2zYkZhr06FVsgTfe/0V5zBYQsDupLjwtbxp5EJvb4pcYyrN8rI5DQdLtumhlbUnDjsfRGQ/U1WLXrURwcGgHsNNqqE+O9Uf9I7KUF6wAQ3Wc8bSbiuefPD/G9PE/6/3hP9IahErVogxOsS2kD5B1ug2GMY5sshUHxhnP/paY5rllroxXPhC+dvsQrzWkEWZjPu0Uu9hHlCpBc/CvbBmpzDpRwDH1m4t7TfcYr+yCfScTvkywESh9Ad76CIYdqKOGng+gnz/FxvEon8IXX9lbyQhoZTXnXYaTWWBathAPOO8G4UoWksnafHcHhp8QtpvgHErG/5FsjcU8mZc6xsodwKMg8jZC+XM0GUQzJ9kbryNXldMruJ5caqtqDx6H53Q0IJhJkIfDHTFC9aF4++nhwsX9k0sLUPIZZq7bzHMMpcPkvzo+cfum8xQ8or4w9WAEiPQgKGTj+rEIQvsYqqihF9ZxQVhytDG+M/Gnc5G1+pkcLnW6J5xXnIlX5eWP/fm57Gpb1re6fgfZtPKFLjfEpzII8MG4sRbq6tTTWgSZp5ahPxH+C+Hp6ERncWWWBfYHDE/tBfNjKvUTw=
  # MATTERMOST_HOOK_URL
  - secure: rmAhyL9fxdKpx4mMjz3Qa6tz8Lu4yKCNX+6qzocjWowjt3Rw44yCFOCAGMmNF9mhlJQFyp1FhbRCpsJ+TZfH9HoXnhxo5ZbIdPyL89mgBqzDvTHM+2oi/8naGHohxgY+0Q7fsFHl9RGiIxHCWJsuPcvzjHQAxxZBdVRWp/u7Xkh877Er2NSGfNMVTbpzsdDmI52Eehrk7UTQIz5VH0e/4nYOJ1HmbA2CPbS+FKher+/e+c8n7H6jM3+tdKOaCay8s0GND0ebSr1iRIhexhOFnBrTgObeUuxVOqx9/o98XZ3khfZIFz88xtWfip8xCwmR1Agb2eu5jeKElVMmiErh9IICI99YKPTALd1m9B0tCXHZ6K8LHiTWajLbXo8GSBDdX3exouByNMxv8y3KJFFZ8J3Dua83k2dLG/qvXPTxAvQ+ges0b7QshIJguqr8bgWBAsfmfIcgJnVU+rUmzhWOiEnuixfnVMcfrKas/5YABpNC1VR1R9Eoa5eg32Gps8QzVn76W6+ZCZkviT8XT5wYfB/gR98fLfvsIHbEuSy0RwherBYrHE5hD3D+sJut3qEMCuv8kaDSRkyI6xPFeNpbMkSbC2QPnF21wTlOvBBxQWuUY5ohLHfYGyGU+etcMeHrAIxjBcYYCMuwXbxklVkGkmswj6/tCscJ3s+kUWe3zR0=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_3ad485b2efab_key -iv $encrypted_3ad485b2efab_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
